Fix heterogeneous query
Fixes:
```
sqlalchemy.exc.ProgrammingError: sqlalchemy.exc.ProgrammingError:
(psycopg2.ProgrammingError) can't adapt type 'Row'
```

The problem happened because the filter was mixing up an integer id and
a Row object .
```
((Pdb)) account_ids
{3, (32276,)}
((Pdb)) tuple(account_ids)[1].owner_id
32276
```