Tabs Tile: Don't explicitly pass in a user to the permission check. Doing so seems to cause an error sometimes: AttributeError: 'MemberData' object has no attribute 'allowed' Refs syslabcom/scrum#384