Define icons view in minimal main template.
Otherwise in the overview-controlpanel pn Plone 6 you get:

    NameError: name 'icons' is not defined

With the new line, on Plone 5 the iconresolver view won't be found, so `icons` will be None. This is fine because icons is not used on Plone 5.